// <auto-generated />
using System;
using Gestion_Regles_Affaires.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gestion_Regles_Affaires.Data.Migrations
{
    [DbContext(typeof(ReglesAffairesContext))]
    [Migration("20210714130834_SeedBusinessRulesData")]
    partial class SeedBusinessRulesData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Gestion_Regles_Affaires.Data.Models.BusinessRules", b =>
                {
                    b.Property<int>("BusinessRulesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("HasParameter")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("ParameterType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParameterValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BusinessRulesId");

                    b.ToTable("BusinessRules");

                    b.HasData(
                        new
                        {
                            BusinessRulesId = 1,
                            HasParameter = false,
                            IsRequired = true,
                            ParameterType = "input",
                            ParameterValue = "",
                            Title = "Nombre de personnes"
                        },
                        new
                        {
                            BusinessRulesId = 2,
                            HasParameter = false,
                            IsRequired = true,
                            ParameterType = "calendar",
                            ParameterValue = "",
                            Title = "Date de début du quart de travail proposée"
                        },
                        new
                        {
                            BusinessRulesId = 3,
                            HasParameter = false,
                            IsRequired = true,
                            ParameterType = "calendar",
                            ParameterValue = "",
                            Title = "Date de fin du quart de travail proposée"
                        },
                        new
                        {
                            BusinessRulesId = 4,
                            HasParameter = false,
                            IsRequired = true,
                            ParameterType = "calendar",
                            ParameterValue = "",
                            Title = "Nombre d'heure au lieu de l'heure de fin"
                        },
                        new
                        {
                            BusinessRulesId = 5,
                            HasParameter = false,
                            IsRequired = true,
                            ParameterType = "input",
                            ParameterValue = "",
                            Title = "Nombre d'heures de pause"
                        },
                        new
                        {
                            BusinessRulesId = 6,
                            HasParameter = true,
                            IsRequired = true,
                            ParameterType = "checkbox",
                            ParameterValue = "Classification 1;Classification 2;Classification 3;Classification 4",
                            Title = "Classification de l'employé"
                        },
                        new
                        {
                            BusinessRulesId = 7,
                            HasParameter = true,
                            IsRequired = false,
                            ParameterType = "dropdown",
                            ParameterValue = "modèle horaire d'appel 1;modèle horaire d'appel 2;modèle horaire d'appel 3;modèle horaire d'appel 4",
                            Title = "Modèle horaire d'appel"
                        },
                        new
                        {
                            BusinessRulesId = 8,
                            HasParameter = false,
                            IsRequired = false,
                            ParameterType = "calendar",
                            ParameterValue = "",
                            Title = "Minimum sur le total heure pour les horaires normales"
                        },
                        new
                        {
                            BusinessRulesId = 9,
                            HasParameter = false,
                            IsRequired = false,
                            ParameterType = "calendar",
                            ParameterValue = "",
                            Title = "Heure total maximum de travail"
                        },
                        new
                        {
                            BusinessRulesId = 10,
                            HasParameter = true,
                            IsRequired = false,
                            ParameterType = "dropdown",
                            ParameterValue = "groupe de contact 1;groupe de contact 2;groupe de contact 3;groupe de contact 4",
                            Title = "Priorisé un groupe de contacts"
                        },
                        new
                        {
                            BusinessRulesId = 11,
                            HasParameter = false,
                            IsRequired = false,
                            ParameterType = "checkbox",
                            ParameterValue = "",
                            Title = "Ne pas recontacter les refusés pour le même jour"
                        },
                        new
                        {
                            BusinessRulesId = 12,
                            HasParameter = false,
                            IsRequired = true,
                            ParameterType = "input",
                            ParameterValue = "",
                            Title = "Appeler en ordre de temps supplémentaire exécuté"
                        },
                        new
                        {
                            BusinessRulesId = 13,
                            HasParameter = false,
                            IsRequired = true,
                            ParameterType = "input",
                            ParameterValue = "",
                            Title = "Ancienneté"
                        },
                        new
                        {
                            BusinessRulesId = 14,
                            HasParameter = false,
                            IsRequired = true,
                            ParameterType = "input",
                            ParameterValue = "",
                            Title = "Employés Temps plein"
                        },
                        new
                        {
                            BusinessRulesId = 15,
                            HasParameter = false,
                            IsRequired = false,
                            ParameterType = "input",
                            ParameterValue = "",
                            Title = "Temps supplémentaire maximum"
                        },
                        new
                        {
                            BusinessRulesId = 16,
                            HasParameter = false,
                            IsRequired = false,
                            ParameterType = "input",
                            ParameterValue = "",
                            Title = "Maximum de temps travaillé"
                        },
                        new
                        {
                            BusinessRulesId = 17,
                            HasParameter = false,
                            IsRequired = false,
                            ParameterType = "input",
                            ParameterValue = "",
                            Title = "Temps avant le poste"
                        },
                        new
                        {
                            BusinessRulesId = 18,
                            HasParameter = false,
                            IsRequired = false,
                            ParameterType = "input",
                            ParameterValue = "",
                            Title = "Temps après le poste"
                        },
                        new
                        {
                            BusinessRulesId = 19,
                            HasParameter = false,
                            IsRequired = false,
                            ParameterType = "checkbox",
                            ParameterValue = "",
                            Title = "Employé en usine en premier"
                        },
                        new
                        {
                            BusinessRulesId = 20,
                            HasParameter = false,
                            IsRequired = false,
                            ParameterType = "checkbox",
                            ParameterValue = "",
                            Title = "Appel seulement sur les heures de travail"
                        },
                        new
                        {
                            BusinessRulesId = 21,
                            HasParameter = false,
                            IsRequired = false,
                            ParameterType = "text area",
                            ParameterValue = "",
                            Title = "Appel différent sur les heures de travail"
                        },
                        new
                        {
                            BusinessRulesId = 22,
                            HasParameter = false,
                            IsRequired = false,
                            ParameterType = "input",
                            ParameterValue = "",
                            Title = "Tentative des non joints"
                        },
                        new
                        {
                            BusinessRulesId = 23,
                            HasParameter = false,
                            IsRequired = false,
                            ParameterType = "input",
                            ParameterValue = "",
                            Title = "Tentative à tous les contacts"
                        },
                        new
                        {
                            BusinessRulesId = 24,
                            HasParameter = false,
                            IsRequired = false,
                            ParameterType = "checkbox",
                            ParameterValue = "",
                            Title = "Division de l'appel"
                        },
                        new
                        {
                            BusinessRulesId = 25,
                            HasParameter = false,
                            IsRequired = false,
                            ParameterType = "checkbox",
                            ParameterValue = "",
                            Title = "Poursuivre avec la même liste"
                        },
                        new
                        {
                            BusinessRulesId = 26,
                            HasParameter = false,
                            IsRequired = false,
                            ParameterType = "input",
                            ParameterValue = "",
                            Title = "Délais entre les appels"
                        },
                        new
                        {
                            BusinessRulesId = 27,
                            HasParameter = false,
                            IsRequired = true,
                            ParameterType = "input",
                            ParameterValue = "",
                            Title = "Priorité de la diffusion"
                        });
                });

            modelBuilder.Entity("Gestion_Regles_Affaires.Data.Models.ModelBusinessRules", b =>
                {
                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<int>("BusinessRulesId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModelId", "BusinessRulesId");

                    b.HasIndex("BusinessRulesId");

                    b.ToTable("ModelBusinessRules");
                });

            modelBuilder.Entity("Gestion_Regles_Affaires.Data.Models.Modele", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModelName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModelId");

                    b.ToTable("Modeles");
                });

            modelBuilder.Entity("Gestion_Regles_Affaires.Data.Models.ModelBusinessRules", b =>
                {
                    b.HasOne("Gestion_Regles_Affaires.Data.Models.BusinessRules", "BusinessRules")
                        .WithMany("ModelBusinessRules")
                        .HasForeignKey("BusinessRulesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_Regles_Affaires.Data.Models.Modele", "Model")
                        .WithMany("ModelBusinessRules")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessRules");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Gestion_Regles_Affaires.Data.Models.BusinessRules", b =>
                {
                    b.Navigation("ModelBusinessRules");
                });

            modelBuilder.Entity("Gestion_Regles_Affaires.Data.Models.Modele", b =>
                {
                    b.Navigation("ModelBusinessRules");
                });
#pragma warning restore 612, 618
        }
    }
}
